#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-zabbix22-update';
event_actions ($event,
     'initialize-default-databases' => '00',
     'nethserver-zabbix22-conf' => '20'
);

templates2events("/etc/httpd/conf.d/zabbix.conf", $event);
templates2events("/etc/zabbix/zabbix_server.conf", $event);

event_services($event,
               'zabbix-server' => 'restart',
               'zabbix-agent' => 'restart',
               'httpd' => 'reload'
);
